### ISSUE TITLE
Clean up package(s) metadata

### ISSUE THREAD

**Issue by dandv** [olragon/meteor-handsontable#14]
Hey @olragon, until we figure out #9, can you please clean up the package a bit?

https://atmospherejs.com/mrt/handsontable should be removed. Try `meteor admin maintainers <your_username>:<your_package> --remove mrt` and `meteor admin set-unmigrated mrt:handsontable`

https://atmospherejs.com/olragon/handsontable doesn't have a README, GitHub URL

https://atmospherejs.com/olragon - would be nice to add your name and Github to your profile

Thanks!

**Comment by olragon** [comment]
Hi @dandv
- [x] https://atmospherejs.com/mrt/handsontable should be removed - asked to remove, update result later
- [x] https://atmospherejs.com/olragon/handsontable doesn't have a README, GitHub URL
- [x] https://atmospherejs.com/olragon - would be nice to add your name and Github to your profile

**Comment by dandv** [comment]
Thanks for adding package metadata for olragon:handsontable.

Did `meteor admin maintainers olragon:handsontable --remove mrt` work?

PS: the website I see in your Atmosphere profile seems down: http://isup.me/http://cun.vn/

**Comment by olragon** [comment]
`meteor admin maintainers olragon:handsontable --remove mrt` do not work with error:

```
Removing a maintainer from olragon:handsontable...
Error from package server: Not a maintainer [400]
```

PS: thank you for let's me known, my domain is expired and acquired by someone :(

**Comment by dandv** [comment]
@tmeasday, can you help?

**Comment by tmeasday** [comment]
Heads up @dandv, you can't remove `mrt` as a maintainer of a `mrt:` package. `mrt` was never a maintainer of `olragon:handsontable`.

**Comment by dandv** [comment]
OK so we're stuck with https://atmospherejs.com/mrt/handsontable, @tmeasday ?

**Comment by tmeasday** [comment]
@dandv, @olragon can mark it unmigrated if he desires. That's what most people have been doing I guess.
